"""empty message

Revision ID: 7c22990aa3e1
Revises: a60eaab47053
Create Date: 2021-01-05 23:55:18.741694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c22990aa3e1'
down_revision = 'a60eaab47053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'words', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    # ### end Alembic commands ###
