"""empty message

Revision ID: a3dd231edad5
Revises: fad5a5dc43bb
Create Date: 2020-11-13 01:13:18.889466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3dd231edad5'
down_revision = 'fad5a5dc43bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'words', 'users', ['group_id'], ['group_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_column('words', 'group_id')
    # ### end Alembic commands ###
