"""empty message

Revision ID: a60eaab47053
Revises: a3dd231edad5
Create Date: 2021-01-05 23:31:46.605617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60eaab47053'
down_revision = 'a3dd231edad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'words', 'groups', ['group_id'], ['id'])
    op.drop_column('words', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('group', sa.VARCHAR(length=30), nullable=True))
    op.drop_constraint(None, 'words', type_='foreignkey')
    # ### end Alembic commands ###
