"""empty message

Revision ID: 447d1c4ac277
Revises: 
Create Date: 2020-11-11 13:25:23.540718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447d1c4ac277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password_hash', sa.String(length=200), nullable=False))
    op.drop_column('users', 'password')
    op.drop_column('users', 'can_edit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_edit', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=200), nullable=False))
    op.drop_column('users', '_password_hash')
    # ### end Alembic commands ###
